import type { TempBand } from '../../shared/api.js';
import type { EventKey, Season } from '../../shared/wardrobe.js';

export type RuleCategory =
  | 'color' | 'pattern' | 'fabric' | 'proportion' | 'weather' | 'occasion'
  | 'shoes' | 'accessory' | 'style' | 'mood' | 'onepiece';

/**
 * Stil bilgi tabanı kaydı. Belirtilen her koşul (events, tempBands, precipitation, seasons, formality,
 * styleTags, moods, requiresOnepiece) bağlamla eşleşmek ZORUNDADIR. Hiç koşulu olmayan kayıtlar `general: true` olmalıdır.
 */
export interface KnowledgeRule {
  id: string;
  category: RuleCategory;
  title: string;
  text: string;
  events?: EventKey[];
  tempBands?: TempBand[];
  precipitation?: Array<'rain' | 'snow'>;
  seasons?: Season[];
  formality?: [number, number];
  styleTags?: string[];
  moods?: string[];
  requiresOnepiece?: boolean;
  general?: boolean;
  /** 1 (düşük) – 3 (yüksek) */
  priority?: number;
}

export const KNOWLEDGE_RULES: KnowledgeRule[] = [
  // ─── RENK ────────────────────────────────────────────────────────────────
  { id: 'color_60_30_10', category: 'color', general: true, priority: 3, title: '60-30-10 dengesi',
    text: 'Bir ana renk (yaklaşık %60), bir ikincil renk (%30) ve küçük bir vurgu (%10) kullan. Vurgu genelde ayakkabı, çanta veya aksesuarda kalır.' },
  { id: 'color_neutral_accent', category: 'color', general: true, priority: 3, title: 'Nötr zemin, tek vurgu',
    text: 'Canlı bir renk kullanıyorsan geri kalan parçaları siyah, beyaz, gri, lacivert, bej veya kahverengi gibi nötrlerde tut. İki canlı renk aynı anda yarışmasın.' },
  { id: 'color_tonal', category: 'color', priority: 2, styleTags: ['Monokromatik'], title: 'Ton-sür-ton',
    text: 'Aynı rengin açık, orta ve koyu tonlarını bir arada kullan (ör. koyu kahve pantolon, sütlü kahve triko, bej kaban). Göz tek renkte kaydığı için boy uzun ve rafine görünür.' },
  { id: 'color_tonal_formal', category: 'color', priority: 2, formality: [3, 5], title: 'Şık kombinde sakin palet',
    text: 'Resmiyet arttıkça palet sadeleşir: lacivert, gri, siyah, bej ve kahverengi ağırlıklı bir kombin, tek bir derin tonla (bordo, zümrüt) zenginleşir.' },
  { id: 'color_complementary', category: 'color', priority: 2, styleTags: ['Tamamlayıcı'], title: 'Tamamlayıcı renkler',
    text: 'Renk çemberinde karşılıklı renkler (mavi–turuncu, mor–sarı, bordo–yeşil) birbirini canlandırır. Birini ana, diğerini küçük bir vurgu olarak kullan; iki büyük parçada eşit dağıtma.' },
  { id: 'color_analogous', category: 'color', general: true, priority: 1, title: 'Komşu renkler',
    text: 'Renk çemberinde yan yana duran renkler (bordo–pembe, mavi–yeşil, sarı–turuncu) yumuşak ve uyumlu geçiş sağlar; kontrast istemediğinde güvenli seçimdir.' },
  { id: 'color_navy_camel', category: 'color', priority: 2, formality: [3, 5], title: 'Lacivert ve kahve/bej',
    text: 'Lacivert; taba, camel, bej ve kahverengiyle klasik ve sıcak bir uyum yakalar. İş ve akşam kombinlerinde siyahtan daha yumuşak bir ciddiyet verir.' },
  { id: 'color_black_white', category: 'color', priority: 2, styleTags: ['Kontrast', 'Minimalist'], title: 'Siyah-beyaz kontrast',
    text: 'Siyah ve beyaz güçlü bir kontrast kurar. Kontrastı dengelemek için üçüncü bir renk eklemek yerine dokularla (deri, triko, saten) çeşitlilik yarat.' },
  { id: 'color_pastel', category: 'color', priority: 2, styleTags: ['Pastel'], title: 'Pastel dengesi',
    text: 'Pastel tonlar beyaz, krem, açık gri veya kum rengiyle ferah durur. Birden fazla pasteli yan yana kullanıyorsan aynı açıklık seviyesinde tut.' },
  { id: 'color_earth_autumn', category: 'color', priority: 2, seasons: ['sonbahar'], title: 'Toprak tonları',
    text: 'Sonbaharda haki, kahverengi, hardal, kiremit ve bordo birbiriyle doğal bir uyum kurar; krem veya ekru bir parça bu paleti aydınlatır.' },
  { id: 'color_summer_light', category: 'color', priority: 2, tempBands: ['warm', 'hot'], title: 'Sıcakta açık renkler',
    text: 'Sıcak havada beyaz, krem, açık mavi ve pastel tonlar hem daha serin tutar hem de ferah görünür. Koyu renkleri alt parçada veya aksesuarda kullan.' },
  { id: 'color_winter_deep', category: 'color', priority: 2, seasons: ['kış'], title: 'Kış tonları',
    text: 'Kışın koyu lacivert, antrasit, bordo ve orman yeşili gibi derin tonlar yün ve kaşe dokularla zenginleşir; açık renkli bir atkı yüze ışık verir.' },
  { id: 'color_shoe_accent', category: 'color', priority: 1, styleTags: ['Maximalist'], title: 'Renkli ayakkabı vurgusu',
    text: 'Nötr bir kombinde renkli ayakkabı veya çanta tek başına vurgu olabilir; aynı rengi küçük bir aksesuarda tekrarlamak bütünlük sağlar.' },
  { id: 'color_repeat', category: 'color', general: true, priority: 1, title: 'Renk tekrarı',
    text: 'Üstteki bir rengi ayakkabı, kemer veya çantada küçük ölçüde tekrarlamak kombini bilinçli ve bütün gösterir.' },
  { id: 'color_texture_monochrome', category: 'color', priority: 2, styleTags: ['Monokromatik', 'Nötr Tonlar'], title: 'Tek renkte doku',
    text: 'Tek renk veya nötr bir palet düz görünmesin diye farklı dokuları (örgü, deri, saten, keten) bir araya getir.' },
  { id: 'color_neutral_layers', category: 'color', priority: 2, styleTags: ['Nötr Tonlar'], title: 'Nötr katmanlar',
    text: 'Bej, taş, gri ve ekruyu katmanlarken tonlar arasında hafif açıklık farkı bırak; tamamen aynı ton kombini soluk gösterebilir.' },
  { id: 'color_contrast_block', category: 'color', priority: 2, styleTags: ['Kontrast'], title: 'Açık–koyu bloklama',
    text: 'Üst ve alt arasında belirgin açıklık farkı (ör. krem üst, koyu lacivert alt) silüeti netleştirir ve fotoğrafta güçlü durur.' },
  { id: 'color_interview_calm', category: 'color', priority: 3, events: ['İş Görüşmesi'], title: 'Görüşmede sakin renkler',
    text: 'İş görüşmesinde dikkati kıyafete değil sana çekecek sakin renkler seç: lacivert, gri, siyah, bej, beyaz. Vurgu gerekiyorsa gömlek veya aksesuarda küçük tut.' },

  // ─── DESEN ───────────────────────────────────────────────────────────────
  { id: 'pattern_single_focus', category: 'pattern', general: true, priority: 3, title: 'Tek desen odak',
    text: 'Kombinde bir desenli parça yeterlidir; diğer parçaları desenin içindeki renklerden birinde ve düz seç.' },
  { id: 'pattern_mixing', category: 'pattern', priority: 2, styleTags: ['Maximalist', 'Vintage'], title: 'Desen karıştırma',
    text: 'İki deseni birleştireceksen desen ölçeklerini farklı tut (ince çizgi ile büyük kare gibi) ve ortak bir renk üzerinden bağla.' },
  { id: 'pattern_stripes_neutral', category: 'pattern', general: true, priority: 1, title: 'Çizgili basic',
    text: 'İnce çizgili (ör. lacivert-beyaz) parçalar neredeyse nötr gibi davranır; düz renkli parçalarla rahatça eşleşir.' },
  { id: 'pattern_animal', category: 'pattern', priority: 2, styleTags: ['Maximalist', 'Y2K'], title: 'Hayvan deseni',
    text: 'Leopar veya yılan derisi deseni tek başına güçlü bir odaktır; siyah, kahverengi, krem gibi nötrlerle kullan.' },
  { id: 'pattern_floral', category: 'pattern', priority: 2, styleTags: ['Romantic', 'Boho'], title: 'Çiçek deseni',
    text: 'Çiçekli parçalar romantik ve bohem stile uyar; desenin zemin rengini ayakkabı veya hırkada tekrarla, sert kontrastlardan kaçın.' },
  { id: 'pattern_graphic', category: 'pattern', priority: 2, formality: [1, 2], title: 'Grafik baskı',
    text: 'Grafik baskılı tişörtler gündelik ve sokak stiline aittir; düz jean, cargo veya jogger ile rahat, sneaker ile tamamlanır.' },
  { id: 'pattern_minimal', category: 'pattern', priority: 2, styleTags: ['Minimalist'], title: 'Minimalist desen',
    text: 'Minimalist stilde desen yerine temiz çizgiler, kaliteli kumaş ve iyi oturan kesim öne çıkar; desen kullanılacaksa ince çizgi veya küçük doku yeterli.' },
  { id: 'pattern_office', category: 'pattern', priority: 2, events: ['Ofis', 'İş Görüşmesi'], title: 'İş ortamında desen',
    text: 'İş ortamında ince çizgi, küçük kare veya hafif doku uygundur; büyük grafik baskılar ve iddialı desenler dikkat dağıtır.' },

  // ─── KUMAŞ / DOKU ────────────────────────────────────────────────────────
  { id: 'fabric_winter', category: 'fabric', priority: 2, tempBands: ['cold', 'freezing'], title: 'Kış dokuları',
    text: 'Soğukta yün, kaşmir, kaşe, kadife ve kalın örgü hem sıcak tutar hem de kombine zengin bir doku katar.' },
  { id: 'fabric_summer', category: 'fabric', priority: 2, tempBands: ['warm', 'hot'], title: 'Yaz kumaşları',
    text: 'Sıcakta keten, pamuk, ipek ve viskon gibi nefes alan, terletmeyen kumaşları seç; sentetik ve kalın kumaşlardan kaçın.' },
  { id: 'fabric_texture_contrast', category: 'fabric', general: true, priority: 1, title: 'Doku kontrastı',
    text: 'Pürüzsüz bir kumaşı dokulu bir kumaşla eşleştirmek (saten ile triko, deri ile yün) kombine derinlik verir.' },
  { id: 'fabric_linen_office', category: 'fabric', priority: 2, events: ['Ofis'], tempBands: ['warm', 'hot'], title: 'Sıcakta ofis kumaşı',
    text: 'Sıcak havada ofiste keten karışımlı pantolon ve pamuklu gömlek hem rahat hem düzgün durur; çok buruşan saf keteni resmi toplantılarda dikkatli kullan.' },
  { id: 'fabric_evening_sheen', category: 'fabric', priority: 2, events: ['Parti', 'Düğün/Davet'], title: 'Gece parlaklığı',
    text: 'Akşam etkinliklerinde saten, ipek, kadife ve hafif parıltılı kumaşlar yakışır; parlaklığı tek parçada tutup diğerlerini mat seç.' },
  { id: 'fabric_denim_on_denim', category: 'fabric', priority: 1, styleTags: ['Streetwear', 'Vintage'], title: 'Kot üstüne kot',
    text: 'Kot ceket ile kot pantolon birlikte giyilecekse tonları belirgin şekilde farklı olsun (açık yıkama ceket, koyu pantolon).' },
  { id: 'fabric_sport_technical', category: 'fabric', priority: 3, events: ['Spor'], title: 'Teknik kumaş',
    text: 'Sporda ter atan, esneyen teknik kumaşları tercih et; pamuk teri tutar ve soğukta üşütür.' },
  { id: 'fabric_velvet_evening', category: 'fabric', priority: 1, events: ['Parti', 'Randevu', 'Düğün/Davet'], tempBands: ['cool', 'cold', 'freezing'], title: 'Kadife akşam',
    text: 'Serin ve soğuk akşamlarda kadife ceket, pantolon veya elbise hem sıcak tutar hem de şık bir doku sağlar.' },
  { id: 'fabric_wet_avoid', category: 'fabric', priority: 2, precipitation: ['rain', 'snow'], title: 'Islak havada kumaş',
    text: 'Yağışlı havada süet ayakkabı, ipek ve açık renk uzun paçalar kolayca lekelenir; deri, suya dayanıklı veya koyu renkli parçaları seç.' },
  { id: 'fabric_travel', category: 'fabric', priority: 2, events: ['Seyahat'], title: 'Seyahat kumaşı',
    text: 'Seyahatte buruşmayan triko, jarse ve esnek kumaşlar uzun yolculukta düzgün kalır ve rahattır.' },

  // ─── ORAN / SİLÜET ───────────────────────────────────────────────────────
  { id: 'prop_volume_balance', category: 'proportion', general: true, priority: 3, title: 'Hacim dengesi',
    text: 'Üst bol veya oversize ise alt parçayı dar ya da düz kesim seç; alt geniş paça ise üst daha oturan olsun. İki bol parça silüeti kaybettirir.' },
  { id: 'prop_rule_of_thirds', category: 'proportion', general: true, priority: 2, title: 'Üçte bir oranı',
    text: 'Vücudu ortadan ikiye bölmek yerine üstü kısa (1/3), altı uzun (2/3) göster: üstü yüksek bel pantolonun içine hafifçe sokmak bacakları uzun gösterir.' },
  { id: 'prop_crop_highwaist', category: 'proportion', priority: 2, styleTags: ['Crop & High-waist'], title: 'Crop ve yüksek bel',
    text: 'Crop üstleri yüksek bel pantolon veya etekle eşleştir; bel çizgisi yükselir ve orantı dengelenir.' },
  { id: 'prop_oversize', category: 'proportion', priority: 2, styleTags: ['Oversize'], title: 'Oversize dengesi',
    text: 'Oversize bir parçayı merkeze al; diğer parçalardan en az birini daha oturan seç ya da kolları kıvırarak ve bileği göstererek hacmi dengele.' },
  { id: 'prop_fitted', category: 'proportion', priority: 2, styleTags: ['Fitted'], title: 'Oturan kesimler',
    text: 'Vücuda oturan kesimlerde kumaşın kalitesi ve boyların doğru olması öne çıkar; çok dar ve gergin duran parçalar yerine vücudu takip eden kesimler seç.' },
  { id: 'prop_wide_leg', category: 'proportion', general: true, priority: 1, title: 'Geniş paça',
    text: 'Geniş paça pantolonla oturan veya içeri sokulmuş bir üst kullan; paça boyu ayakkabının yarısını kapatacak uzunlukta dursun.' },
  { id: 'prop_vertical_line', category: 'proportion', general: true, priority: 1, title: 'Dikey çizgi',
    text: 'Açık bırakılmış uzun bir ceket veya aynı tondaki üst-alt, göze dikey bir çizgi çizer ve boyu uzun gösterir.' },
  { id: 'prop_blazer_length', category: 'proportion', priority: 2, events: ['Ofis', 'İş Görüşmesi'], title: 'Ceket boyu',
    text: 'Blazer omuzdan taşmamalı, kolları bileği geçmemeli; kısa ceketleri yüksek bel altlarla, uzun ceketleri düz ve dar kesimlerle kullan.' },
  { id: 'prop_hem_shoes', category: 'proportion', general: true, priority: 1, title: 'Paça ve ayakkabı',
    text: 'Dar paça sneaker ve loaferla temiz durur; geniş ve uzun paçalar hafif topuk veya kalın taban ister.' },
  { id: 'prop_belt_waist', category: 'proportion', priority: 1, styleTags: ['Romantic', 'Fitted'], title: 'Bel vurgusu',
    text: 'Bol bir elbise veya ceketi kemerle bele oturtmak silüeti tanımlar ve kombine zarif bir odak kazandırır.' },
  { id: 'prop_layer_lengths', category: 'proportion', priority: 2, styleTags: ['Katmanlı'], title: 'Katman uzunlukları',
    text: 'Katmanlı görünümde en içteki parça en kısa, dış katman en uzun olsun ya da katmanlar belirgin şekilde farklı boylarda görünsün.' },
  { id: 'prop_dark_bottom', category: 'proportion', general: true, priority: 1, title: 'Odak noktası',
    text: 'Göz açık renklere ve desenlere çekilir: öne çıkarmak istediğin bölgeyi açık veya desenli, dengelemek istediğin bölgeyi koyu ve düz seç.' },

  // ─── HAVA / KATMANLAMA ───────────────────────────────────────────────────
  { id: 'weather_sandwich', category: 'weather', priority: 2, tempBands: ['cool', 'cold'], title: 'Sandviç katmanlama',
    text: 'İçte ince bir tişört veya bluz, ortada gömlek/hırka/triko, dışta yapılandırılmış bir ceket ya da kaban: hava değişse de katman çıkararak rahat edersin.' },
  { id: 'weather_cold_base', category: 'weather', priority: 3, tempBands: ['cold', 'freezing'], title: 'Soğukta iç kat',
    text: 'Soğukta tek kalın parça yerine ince yün veya termal bir iç kat ile iyi bir kaban daha sıcak tutar; kapalı mekanda da rahat çıkarılır.' },
  { id: 'weather_freezing', category: 'weather', priority: 3, tempBands: ['freezing'], title: 'Dondurucu soğuk',
    text: 'Donma noktası civarında kalın ve rüzgar geçirmeyen bir mont/kaban, kapalı bot ve atkı-bere-eldiven gerekir; açık ayakkabı ve ince kumaş alt giyimden kaçın.' },
  { id: 'weather_rain', category: 'weather', priority: 3, precipitation: ['rain'], title: 'Yağmur',
    text: 'Yağışta su geçirmez bir dış katman (trençkot, yağmurluk, deri ceket) ve suya dayanıklı ayakkabı seç; kanvas ve süet ayakkabılar ıslanır.' },
  { id: 'weather_snow', category: 'weather', priority: 3, precipitation: ['snow'], title: 'Kar',
    text: 'Karda kaymaz tabanlı, su geçirmez botlar ve paçası botun içine girebilecek ya da bot üstünde duran alt giyim kullan.' },
  { id: 'weather_swing', category: 'weather', priority: 2, tempBands: ['mild', 'cool'], title: 'Sabah-akşam farkı',
    text: 'Ilık ve serin günlerde sabah ile öğle arasındaki farka karşı kolayca çıkarılabilen hafif bir katman (hırka, overshirt, ince ceket) taşı.' },
  { id: 'weather_mild_light_layer', category: 'weather', priority: 2, tempBands: ['mild'], title: 'Ilık hava',
    text: 'Ilık havada kalın dış giyime gerek yok; ince blazer, kot ceket veya hırka kombini tamamlar ve akşam serinliğinde işe yarar.' },
  { id: 'weather_warm_breathable', category: 'weather', priority: 3, tempBands: ['warm', 'hot'], title: 'Sıcak hava',
    text: 'Sıcak havada tek kat, nefes alan kumaş ve biraz bol kesim tercih et; kalın dış giyim ve bot gerekmez.' },
  { id: 'weather_hot', category: 'weather', priority: 3, tempBands: ['hot'], title: 'Çok sıcak',
    text: 'Çok sıcakta açık renkli, bol kesim, tek katlı parçalar ile sandalet, espadril veya nefes alan sneaker seç; şapka ve güneş gözlüğü koruma sağlar.' },
  { id: 'weather_rain_coat', category: 'weather', priority: 2, precipitation: ['rain'], title: 'Yağmurda şıklık',
    text: 'Trençkot yağışlı günlerde hem gündelik hem iş kombinlerini şık tutar; şemsiye kullanılacaksa daha ince bir su geçirmez ceket yeterlidir.' },
  { id: 'weather_cool_outer', category: 'weather', priority: 2, tempBands: ['cool'], title: 'Serin hava dış katmanı',
    text: 'Serin havada trençkot, deri ceket, kalın blazer veya kaşe ceket ağırlığında bir dış katman yeterlidir; şişme mont fazla gelir.' },
  { id: 'weather_indoor_outdoor', category: 'weather', priority: 1, tempBands: ['cold', 'freezing'], title: 'İç–dış mekan farkı',
    text: 'Soğukta kaban çıkarıldığında alttaki kombin etkinliğe uygun görünmeli; en şık katmanı içte, en sıcak katmanı dışta tut.' },
  { id: 'weather_winter_shoes', category: 'weather', priority: 2, tempBands: ['cold', 'freezing'], title: 'Kış ayakkabısı',
    text: 'Soğuk havada kapalı ve kalın tabanlı ayakkabı veya bot giy; ince tabanlı ayakkabılar yerden gelen soğuğu geçirir.' },
  { id: 'weather_office_ac', category: 'weather', priority: 1, events: ['Ofis'], tempBands: ['warm', 'hot'], title: 'Klimalı ofis',
    text: 'Sıcak günlerde klimalı ofis için ince bir hırka veya ceketi yanında bulundur.' },

  // ─── ETKİNLİK ────────────────────────────────────────────────────────────
  { id: 'occ_casual_base', category: 'occasion', priority: 3, events: ['Gündelik'], title: 'Gündelik formül',
    text: 'Temiz bir basic üst, iyi oturan bir jean veya chino ve sade bir sneaker gündelik kombinin güvenli temelidir.' },
  { id: 'occ_casual_elevate', category: 'occasion', priority: 2, events: ['Gündelik'], formality: [2, 3], title: 'Gündeliği bir tık şıklaştır',
    text: 'Gündelik bir kombini bir blazer, loafer veya kaliteli bir triko ile smart casual seviyesine taşıyabilirsin.' },
  { id: 'occ_casual_statement', category: 'occasion', priority: 1, events: ['Gündelik', 'Okul'], title: 'Tek iddialı parça',
    text: 'Gündelik kombinde tek bir iddialı parça (renkli ceket, desenli gömlek, dikkat çeken ayakkabı) yeterlidir; gerisi sade kalsın.' },
  { id: 'occ_office_formula', category: 'occasion', priority: 3, events: ['Ofis'], title: 'Ofis formülü',
    text: 'Kumaş pantolon veya düz kesim etek, gömlek/bluz/ince triko ve loafer veya sade deri ayakkabı; soğukta üstüne blazer veya kaban.' },
  { id: 'occ_office_color', category: 'occasion', priority: 2, events: ['Ofis'], title: 'Ofiste renk',
    text: 'Ofiste nötr bir temel üzerine tek bir renk vurgusu profesyonel ama sıkıcı olmayan bir görünüm sağlar.' },
  { id: 'occ_office_avoid', category: 'occasion', priority: 2, events: ['Ofis', 'İş Görüşmesi'], title: 'İş ortamında kaçınılacaklar',
    text: 'İş ortamında şort, terlik, spor tayt, yırtık jean ve çok dekolteli parçalardan kaçın; kurumun kültürü daha rahatsa bile temiz ve ütülü görün.' },
  { id: 'occ_interview_level', category: 'occasion', priority: 3, events: ['İş Görüşmesi'], title: 'Bir tık şık',
    text: 'Görüşmeye şirketin günlük kıyafet düzeninden bir seviye daha şık git: yapılandırılmış bir ceket veya blazer güvenilir ve hazırlıklı gösterir.' },
  { id: 'occ_interview_formula', category: 'occasion', priority: 3, events: ['İş Görüşmesi'], title: 'Görüşme formülü',
    text: 'Oturan bir blazer, sade gömlek veya bluz, kumaş pantolon ya da diz hizası etek ve temiz, kapalı deri ayakkabı en güvenli görüşme kombinidir.' },
  { id: 'occ_interview_details', category: 'occasion', priority: 2, events: ['İş Görüşmesi'], title: 'Görüşmede ayrıntılar',
    text: 'Görüşmede aksesuar ve takıları sade tut, kıyafetin ütülü ve ayakkabının temiz olduğundan emin ol; rahat edemeyeceğin yeni ayakkabılardan kaçın.' },
  { id: 'occ_date_comfort', category: 'occasion', priority: 3, events: ['Randevu'], title: 'Randevuda kendin ol',
    text: 'Randevuda kendini rahat hissettiğin ama özen gösterdiğin bir kombin seç; hiç denemediğin, sürekli düzeltmen gereken parçalar seni gergin gösterir.' },
  { id: 'occ_date_texture', category: 'occasion', priority: 2, events: ['Randevu'], title: 'Dokuyla özen',
    text: 'Saten bir bluz, kaliteli bir triko veya deri bir ceket gibi tek bir dokulu parça randevu kombinini abartmadan özel kılar.' },
  { id: 'occ_date_venue', category: 'occasion', priority: 2, events: ['Randevu'], title: 'Mekana göre',
    text: 'Akşam yemeği için smart casual, açık hava veya kahve buluşması için rahat şık bir kombin seç; mekanın havasına uy.' },
  { id: 'occ_party_night', category: 'occasion', priority: 3, events: ['Parti'], title: 'Gece dokuları',
    text: 'Partide saten, deri, kadife veya ölçülü parıltılı parçalar öne çıkar; koyu bir zemin üzerinde tek parlak parça en etkili sonucu verir.' },
  { id: 'occ_party_dance', category: 'occasion', priority: 2, events: ['Parti'], title: 'Uzun gece',
    text: 'Uzun süre ayakta kalacaksan veya dans edeceksen şık ama rahat ayakkabı seç (blok topuk, şık bot, deri sneaker).' },
  { id: 'occ_party_cocktail', category: 'occasion', priority: 2, events: ['Parti'], formality: [3, 5], title: 'Kokteyl',
    text: 'Kokteyl davetinde midi elbise ya da şık bir pantolon ile saten veya ipek bir üst, zarif ayakkabıyla tamamlanır.' },
  { id: 'occ_wedding_dresscode', category: 'occasion', priority: 3, events: ['Düğün/Davet'], title: 'Davet kıyafet kuralı',
    text: 'Gündüz davetlerinde açık ve pastel tonlar, akşam davetlerinde koyu ve derin tonlar ile daha parlak kumaşlar uygundur.' },
  { id: 'occ_wedding_white', category: 'occasion', priority: 3, events: ['Düğün/Davet'], title: 'Beyazdan kaçın',
    text: 'Düğünlerde gelinle karışmamak için baştan aşağı beyaz veya kırık beyaz kombinlerden kaçın.' },
  { id: 'occ_wedding_formula', category: 'occasion', priority: 3, events: ['Düğün/Davet'], title: 'Davet formülü',
    text: 'Takım elbise veya şık kumaş pantolon ile ceket, ya da midi/uzun elbise; deri ve temiz ayakkabı, ölçülü takılarla tamamlanır. Jean ve spor ayakkabı davet için uygun değildir.' },
  { id: 'occ_wedding_henna', category: 'occasion', priority: 1, events: ['Düğün/Davet'], formality: [3, 4], title: 'Kına ve nişan',
    text: 'Kına ve nişan gibi daha samimi davetlerde renkli ve daha rahat kesimler kullanılabilir; yine de şık ayakkabı ve özenli detaylar korunur.' },
  { id: 'occ_sport_functional', category: 'occasion', priority: 3, events: ['Spor'], title: 'Spor işlevselliği',
    text: 'Sporda hareketi kısıtlamayan, esneyen ve ter atan parçalar seç; şıklık yerine konfor ve güvenlik öncelikli.' },
  { id: 'occ_sport_shoes', category: 'occasion', priority: 3, events: ['Spor'], title: 'Doğru spor ayakkabısı',
    text: 'Koşu, yürüyüş veya salon için uygun tabanlı spor ayakkabısı giy; moda sneaker ve düz tabanlı ayakkabılar sakatlık riskini artırır.' },
  { id: 'occ_sport_cold', category: 'occasion', priority: 2, events: ['Spor'], tempBands: ['cool', 'cold', 'freezing'], title: 'Soğukta spor',
    text: 'Soğukta dışarıda spor yaparken ter atan bir iç kat, ince bir ara kat ve rüzgar geçirmeyen bir dış kat kullan; ısındıkça katman çıkar.' },
  { id: 'occ_travel_comfort', category: 'occasion', priority: 3, events: ['Seyahat'], title: 'Seyahatte konfor',
    text: 'Yolculukta rahat bel, esnek kumaş ve kolay çıkarılan katmanlar seç; uçak ve otobüs içi sıcaklığı değişkendir.' },
  { id: 'occ_travel_capsule', category: 'occasion', priority: 2, events: ['Seyahat'], title: 'Seyahat kapsülü',
    text: 'Seyahat için birbirleriyle kombinlenebilen nötr bir renk paletinde az sayıda parça seç; her üst her altla eşleşebilsin.' },
  { id: 'occ_travel_shoes', category: 'occasion', priority: 2, events: ['Seyahat'], title: 'Seyahat ayakkabısı',
    text: 'Çok yürünecek seyahatlerde önceden alışılmış, rahat tabanlı ayakkabı seç; güvenlik kontrolünde kolay çıkarılabilmesi de avantajdır.' },
  { id: 'occ_school_day', category: 'occasion', priority: 2, events: ['Okul'], title: 'Uzun okul günü',
    text: 'Okulda uzun gün boyunca rahat edeceğin, sınıf ile dışarı arasında katman değiştirebileceğin parçalar seç.' },
  { id: 'occ_school_bag', category: 'occasion', priority: 1, events: ['Okul'], title: 'Çantayla uyum',
    text: 'Sırt çantası omuzdaki parçaları ezer; ince ve kaygan kumaşlar yerine dayanıklı üstler ve sade bir renk paleti kullan.' },

  // ─── AYAKKABI ────────────────────────────────────────────────────────────
  { id: 'shoes_define_formality', category: 'shoes', general: true, priority: 3, title: 'Ayakkabı resmiyeti belirler',
    text: 'Aynı kombin sneaker ile gündelik, loafer ile smart casual, oxford veya topukluyla resmi görünür; ayakkabıyı etkinliğin resmiyetine göre seç.' },
  { id: 'shoes_leather_match', category: 'shoes', priority: 2, formality: [3, 5], title: 'Deri tonu uyumu',
    text: 'Şık kombinlerde kemer ve ayakkabının deri tonu aynı ailede olsun (siyah–siyah, kahve–kahve).' },
  { id: 'shoes_white_sneaker', category: 'shoes', priority: 2, formality: [2, 3], title: 'Beyaz sneaker köprüsü',
    text: 'Temiz, sade beyaz deri sneaker gündelik ile smart casual arasında köprü kurar; blazer ve kumaş pantolonla bile modern durur.' },
  { id: 'shoes_loafer', category: 'shoes', priority: 2, events: ['Ofis', 'Randevu'], title: 'Loafer',
    text: 'Loafer kumaş pantolon, chino ve düz paça jeanle uyumlu, çok yönlü bir ayakkabıdır; ofis ve akşam yemeği için güvenli seçimdir.' },
  { id: 'shoes_formal', category: 'shoes', priority: 3, events: ['İş Görüşmesi', 'Düğün/Davet'], title: 'Resmi ayakkabı',
    text: 'Resmi etkinliklerde oxford, derby, şık loafer, stiletto veya zarif topuklu gibi kapalı ve bakımlı deri ayakkabılar seç.' },
  { id: 'shoes_boots_trousers', category: 'shoes', priority: 2, tempBands: ['cool', 'cold', 'freezing'], title: 'Bot ve paça',
    text: 'Botla dar paça pantolonu botun içine veya hemen üstüne düşecek şekilde, geniş paçayı ise botun üzerini örtecek şekilde kullan.' },
  { id: 'shoes_summer', category: 'shoes', priority: 2, tempBands: ['warm', 'hot'], formality: [1, 3], title: 'Yaz ayakkabısı',
    text: 'Sıcak günlerde sandalet, espadril veya file sneaker ayağı rahatlatır; resmi ortamlarda açık ayakkabı yerine loafer tercih et.' },
  { id: 'shoes_neutral', category: 'shoes', general: true, priority: 1, title: 'Nötr ayakkabı',
    text: 'Siyah, kahverengi, beyaz ve bej ayakkabılar neredeyse her kombinle çalışır; renkli ayakkabıyı kombinin tek vurgusu olarak kullan.' },

  // ─── AKSESUAR ────────────────────────────────────────────────────────────
  { id: 'acc_single_focus', category: 'accessory', general: true, priority: 2, title: 'Tek odak aksesuar',
    text: 'Aksesuarlarda tek bir odak seç (iddialı küpe, dikkat çeken çanta veya saat); hepsi birden öne çıkınca kombin kalabalıklaşır.' },
  { id: 'acc_office', category: 'accessory', priority: 2, events: ['Ofis', 'İş Görüşmesi'], title: 'İş aksesuarı',
    text: 'İş ortamında sade bir saat, deri kemer ve yapılandırılmış bir çanta profesyonel görünümü tamamlar.' },
  { id: 'acc_bag_scale', category: 'accessory', general: true, priority: 1, title: 'Çanta orantısı',
    text: 'Gündelikte büyük ve yumuşak çantalar, şık etkinliklerde küçük ve yapılandırılmış çantalar daha uyumlu durur.' },
  { id: 'acc_evening_jewelry', category: 'accessory', priority: 2, events: ['Parti', 'Düğün/Davet'], title: 'Gece takıları',
    text: 'Akşam etkinliklerinde takıları biraz daha belirgin kullanabilirsin; kıyafet parlaksa takıyı sade, kıyafet sadeyse takıyı iddialı tut.' },
  { id: 'acc_sun', category: 'accessory', priority: 2, tempBands: ['warm', 'hot'], title: 'Güneş aksesuarı',
    text: 'Güneşli ve sıcak havada şapka ve güneş gözlüğü hem koruma sağlar hem de kombini tamamlar.' },
  { id: 'acc_winter_link', category: 'accessory', priority: 2, tempBands: ['cold', 'freezing'], title: 'Atkı ve bere',
    text: 'Atkı ve bere kışın kombinin renk bağlantısını kurabilir: kabanla tonlu ya da ayakkabı veya çantayla aynı renkte seç.' },

  // ─── STİL ETİKETLERİ ─────────────────────────────────────────────────────
  { id: 'style_minimalist', category: 'style', priority: 3, styleTags: ['Minimalist'], title: 'Minimalist',
    text: 'Az parça, temiz çizgi, nötr palet ve iyi kumaş. Logosuz, desensiz parçalar ve tek bir yapılandırılmış siluet minimalist görünümü taşır.' },
  { id: 'style_maximalist', category: 'style', priority: 3, styleTags: ['Maximalist'], title: 'Maximalist',
    text: 'Renk, desen ve dokuyu cesurca birleştir ama ortak bir renk veya tema üzerinden bağla ki kombin kaotik değil bilinçli dursun.' },
  { id: 'style_classic', category: 'style', priority: 3, styleTags: ['Klasik'], title: 'Klasik',
    text: 'Blazer, düz gömlek, kumaş pantolon, trençkot ve loafer gibi zamansız parçalar; lacivert, bej, beyaz ve kahverengi paleti.' },
  { id: 'style_vintage', category: 'style', priority: 3, styleTags: ['Vintage'], title: 'Vintage',
    text: 'Bir veya iki dönem parçasını (yüksek bel kot, kareli blazer, kolej hırka) modern ve sade parçalarla dengele; baştan aşağı kostüm gibi görünmesin.' },
  { id: 'style_streetwear', category: 'style', priority: 3, styleTags: ['Streetwear'], title: 'Streetwear',
    text: 'Oversize üstler, cargo veya geniş paça pantolon, iddialı sneaker ve katmanlı parçalar; grafik veya logolu tek bir odak parça.' },
  { id: 'style_preppy', category: 'style', priority: 3, styleTags: ['Preppy'], title: 'Preppy',
    text: 'Oxford gömlek, v yaka triko veya hırka, chino ve loafer; lacivert, bordo, yeşil ve kareli detaylarla düzenli bir kolej havası.' },
  { id: 'style_boho', category: 'style', priority: 3, styleTags: ['Boho'], title: 'Boho',
    text: 'Akışkan kumaşlar, etnik ve çiçekli desenler, toprak tonları, süet ve hasır dokular; katmanlı takılar ve rahat silüetler.' },
  { id: 'style_dark_academia', category: 'style', priority: 3, styleTags: ['Dark Academia'], title: 'Dark Academia',
    text: 'Tüvit ve yün, kareli ve balıkçıksırtı desenler, koyu kahve, haki, bordo ve lacivert; oxford ayakkabı ve katmanlı triko-gömlek.' },
  { id: 'style_y2k', category: 'style', priority: 3, styleTags: ['Y2K'], title: 'Y2K',
    text: 'Düşük bel ve bol paça, crop üstler, parlak renkler ve oyuncu aksesuarlar; bir iki Y2K detayını sade parçalarla dengelemek daha güncel durur.' },
  { id: 'style_sporty', category: 'style', priority: 3, styleTags: ['Sporty'], title: 'Sporty',
    text: 'Eşofman, sweatshirt, teknik ceket ve sneaker; spor parçaları temiz bir palet ve bir şık parçayla (ör. yün kaban) şehir kombinine çevirebilirsin.' },
  { id: 'style_business_casual', category: 'style', priority: 3, styleTags: ['Business Casual'], title: 'Business Casual',
    text: 'Kravatsız, takım olmayan ama özenli: chino veya kumaş pantolon, gömlek veya triko, blazer ve loafer/deri sneaker.' },
  { id: 'style_romantic', category: 'style', priority: 3, styleTags: ['Romantic'], title: 'Romantic',
    text: 'Yumuşak kumaşlar, fırfır ve dantel detaylar, pastel ve pudra tonlar; akışkan silüetleri belde tanımlayarak zarif bir görünüm yakala.' },

  // ─── RUH HALİ ────────────────────────────────────────────────────────────
  { id: 'mood_energetic', category: 'mood', priority: 2, moods: ['Enerjik'], title: 'Enerjik',
    text: 'Enerjik bir ruh hali için canlı bir vurgu rengi veya hareketli bir parça (renkli sneaker, desenli gömlek) ve rahat bir silüet seç.' },
  { id: 'mood_minimal', category: 'mood', priority: 2, moods: ['Minimalist'], title: 'Sade ruh hali',
    text: 'Sade bir gün için nötr tonlar, az parça ve düz kumaşlar; tek bir kaliteli detay yeterli.' },
  { id: 'mood_romantic', category: 'mood', priority: 2, moods: ['Romantik'], title: 'Romantik',
    text: 'Romantik bir his için yumuşak dokular, akışkan kumaşlar ve pastel veya derin şarap tonları kullan.' },
  { id: 'mood_serious', category: 'mood', priority: 2, moods: ['Ciddi'], title: 'Ciddi',
    text: 'Ciddi ve güven veren bir görünüm için yapılandırılmış parçalar, koyu nötrler ve temiz, keskin çizgiler seç.' },
  { id: 'mood_relaxed', category: 'mood', priority: 2, moods: ['Rahat'], title: 'Rahat',
    text: 'Rahat bir gün için yumuşak kumaşlar ve hareket alanı bırakan kesimler seç; özenli görünmek için tek bir derli toplu parça (düzgün bir ceket veya temiz sneaker) yeterli.' },

  // ─── TEK PARÇA ───────────────────────────────────────────────────────────
  { id: 'onepiece_layer', category: 'onepiece', priority: 3, requiresOnepiece: true, title: 'Elbise ve katman',
    text: 'Elbise veya tulumun üzerine blazer, kot ceket veya hırka eklemek kombinin resmiyetini ve sıcaklığını ayarlamanın en kolay yoludur.' },
  { id: 'onepiece_winter', category: 'onepiece', priority: 3, requiresOnepiece: true, tempBands: ['cool', 'cold', 'freezing'], title: 'Soğukta elbise',
    text: 'Soğukta elbiseyi kalın çorap, bot ve elbiseden uzun ya da ona yakın boyda bir kabanla giy.' },
  { id: 'onepiece_jumpsuit', category: 'onepiece', priority: 2, requiresOnepiece: true, title: 'Tulum',
    text: 'Tulumu kemerle bele oturt; paça boyuna göre sneaker, sandalet veya hafif topuklu ayakkabı seç.' },
  { id: 'onepiece_dress_shoes', category: 'onepiece', priority: 2, requiresOnepiece: true, events: ['Ofis', 'Randevu', 'Parti', 'Gündelik'], title: 'Elbisenin resmiyeti',
    text: 'Aynı elbise sneaker ve kot ceketle gündelik, loafer ve blazerla ofis, topuklu ve saten detaylarla akşam kombinine dönüşür.' },
];
